-- 코드를 작성해주세요
SELECT 
    DISTINCT(ID),
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM 
    DEVELOPERS
JOIN
    (SELECT CODE FROM SKILLCODES WHERE NAME REGEXP 'Python|C#') S
WHERE
    SKILL_CODE & S.CODE
ORDER BY 
    ID
