// 여집합.
/* LEFT JOIN을 사용했음에 유의하라.*/
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O 
LEFT JOIN ANIMAL_INS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
-- 제외하고자 하는 집합의 id에 대해 IS NULL 조건 설정
ORDER BY O.ANIMAL_ID
