-- 코드를 작성해주세요

-- 내 답안
SELECT 
    DISTINCT(ID),	
    EMAIL,	
    FIRST_NAME,	
    LAST_NAME
FROM 
    DEVELOPERS AS D
JOIN
    (SELECT CODE FROM SKILLCODES WHERE CATEGORY = 'Front End') AS S
ON
    D.SKILL_CODE & S.CODE > 0
ORDER BY 
    ID

-- 프로그래머스 답안
SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM
  SKILLCODES
  JOIN DEVELOPERS ON CODE & SKILL_CODE
WHERE CATEGORY = 'Front End'
ORDER BY ID;
