//LOCATE <-> FIND 혼동 2. FIND는 없다.

-- 코드를 입력하세요
SELECT WAREHOUSE_ID,	WAREHOUSE_NAME,	ADDRESS,	IFNULL(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE LEFT(ADDRESS, LOCATE(' ', ADDRESS)) = '경기도'
ORDER BY WAREHOUSE_ID
